### ISSUE TITLE
jmodem sources

### ISSUE THREAD

**Issue by bestulin** [romanz/audiomodem-android#5]
Hi @romanz 
Can you share the source code for jmodem library used in your audiomodem-android app?

**Comment by romanz** [comment]
I need to find it first :)

**Comment by bestulin** [comment]
Thank you! I have been playing around with your library, and it works great! The only issue I ran into is that GC is going crazy when I call 
`jmodem.Main.receive(input, output);`
Hence my request :)

**Comment by bestulin** [comment]
Hey @romanz , any luck finding the sources for jmodem library?

**Comment by romanz** [comment]
Not yet - but meanwhile you can try http://quiet.github.io/quiet/ :)
It has also a JS implementation: https://quiet.github.io/quiet-js/

Note that it's not compatible with my app - but I think that it has more features and probably better performance.

**Comment by bestulin** [comment]
Thanks, I will take a look

**Comment by gurtajs4** [comment]
Hi Romanz

Can you please provide the source code for jmodem library.
I want to enable synchronization and support larger data transefer

Regards,
Gurtaj

**Comment by romanz** [comment]
The sources for the audio MODEM library are here: https://github.com/romanz/jmodem
