### ISSUE TITLE
Length of sending text

### ISSUE THREAD

**Issue by nishantraju** [romanz/audiomodem-android#6]
how can i increase the length of text file. It only receive certain lines of text.

**Comment by romanz** [comment]
Current implementation supports only small messages (<250B, IIRC).

**Comment by nishantraju** [comment]
Can you please tell me how to increase length.

**Comment by romanz** [comment]
This requires non-trivial work on the decoder implementation, for which unfortunately I don't have time :(

**Comment by romanz** [comment]
Please find the sources for the audio MODEM library here: https://github.com/romanz/jmodem
